version: "2"

services:

 nginx:
   image: nginx:1.11
   ports:
    - 4212:4212
   volumes:
    - ./docker/nginx/templates/default.conf.template:/etc/nginx/conf.d/default.conf.template
    - ./docker/nginx/entrypoint.sh:/entrypoint.sh
    - ./dist:/usr/local/src/moniic-ui-v3
   environment:
    - NGINX_PORT=4212
    - DOCUMENT_ROOT=/usr/local/src/moniic-ui-v3
   command: "/bin/bash /entrypoint.sh"
